import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import "lenis/dist/lenis.css";
import Lenis from "lenis";
import SmoothScroll from "./components/SmoothScroll";
import SitePreloader from "./components/SitePreloader";
import BeautyMenu from "./components/home/OrchestratedMenu";
import SiteFooter from "./components/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <SitePreloader brandName="Brandify Digital" />
        <BeautyMenu/> 
        <SmoothScroll>
          {children}
          <SiteFooter/>
        </SmoothScroll>
      </body>
    </html>
  );
}
